### ISSUE TITLE
Fcitx 5 appears in the applications menu

### ISSUE THREAD

**Issue by Odi-3** [elementary/switchboard-plug-locale#177]
### What Happened?

Fcitx 5 appears in the applications menu

### Steps to Reproduce

1. Open applications menu

### Expected Behavior

I believe this is a issue as this is a system package (or dependency) and not an end user application.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
I'll close this since new version was released. It won't delete Fcitx 5 but at least will prevent it from installing.

**Comment by Odi-3** [comment]
So what should we do?  Will an updated ISO be released?
