### ISSUE TITLE
Clicking on plug while authentication dialog open results in persistent "Not responding" warning

### ISSUE THREAD

**Issue by jeremypw** [elementary/switchboard-plug-locale#204]
### What Happened?

Affects Power and Locale plugs (at least).

Some plugs require authentication before certain operations are carried out.  If while the polkit authentication dialog is open the original plug window is focused (by clicking or Alt-Tab) then after a few seconds a "System Settings Not responding" warning window appears.  If the "Wait" button is pressed and the authentication dialog closed then the "Not responding" window keeps reappearing even though the plug is in fact responding normally.  It also keeps reappearing if you navigate back to the start.  Only closing Switchboard altogether stops it.

### Steps to Reproduce

1. Open the Locale plug
2. Click on "Set System Language" - the authentication dialog opens
3. Click on the plug window and wait
4. The "Not responding" window appears and cannot be stopped reappearing except by quitting Switchboard

### Expected Behavior

It should not be possible to interact with the plug while the authentication dialog is open.  When the app is responding the "Not responding" dialog should not reappear.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by ryonakano** [comment]
Leaving a note that this does no longer occurs with "Set System Language" button thanks to #205. However, it still occurs when trying to installing/removing the language.
