### ISSUE TITLE
After login always shows up empty

### ISSUE THREAD

**Issue by peteruithoven** [elementary/switchboard-plug-locale#21]
When I go to the Language & Region settings it shows up empty: 
![screenshot from 2017-05-14 14 56 03](https://cloud.githubusercontent.com/assets/523210/26033975/87e99ae0-38b5-11e7-93de-199dba9e795b.png)

When I then remove the lock, and attempt to add English the list is suddenly filled: 
![locale mp4](https://cloud.githubusercontent.com/assets/523210/26033993/f1bd994e-38b5-11e7-8b37-963c917b5a2f.gif)

When I then logout and login again the list is empty again. 

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```
![screenshot from 2017-05-14 15 01 51](https://cloud.githubusercontent.com/assets/523210/26034022/49933fca-38b6-11e7-9d0a-eb605a78a4f9.png)

Let me know if I can provide more information.

**Comment by Romdef** [comment]
Same problem on my current installation and on a fresh one.

**Comment by peteruithoven** [comment]
Thanks for the quick fix @danrabbit
