### ISSUE TITLE
Blacklist certain check-language-support recommended packages [$35]

### ISSUE THREAD

**Issue by leonardo-lemos** [elementary/switchboard-plug-locale#66]
The Locale Plug installs all the packages listed in the `check-language-support | sed 's/ /\n/g' | grep -v ibus`, for example:

`fcitx-chewing
fcitx-hangul
fcitx-module-cloudpinyin
fcitx-pinyin
fcitx-sunpinyin
fcitx-table-cangjie
fcitx-table-wubi
fcitx-ui-qimpanel
fcitx-unikey`

We need it to install just the missing packages for installed languages, using the `-l` argument in `check-language-support` script.

**Comment by codygarver** [comment]
After some discussion on Slack, it seems the best way to maintain the usefulness of `check-language-support` without making its output too specific is to blacklist undesirable packages it may recommend.

e.g.
```
fcitx-chewing 
fcitx-hangul 
fcitx-module-cloudpinyin 
fcitx-pinyin 
fcitx-sunpinyin 
fcitx-table-cangjie 
fcitx-table-wubi 
fcitx-ui-qimpanel 
fcitx-unikey
```

**Comment by codygarver** [comment]
This issue has a bounty on it [at Bountysource](https://www.bountysource.com/issues/60241526-blacklist-certain-language-selector-check-language-support-recommended-packages).
