### ISSUE TITLE
South African number system uses incorrect decimal and 1000s separator symbols.

### ISSUE THREAD

**Issue by EidoJ** [elementary/switchboard-plug-locale#69]
Using the South African formats in the Language & Region settings formats numbers with a '.' as the decimal point and a ',' as the 1000s separator. The standard in South Africa is to use a ',' for the decimal point and a ' ' (space) as the 1000s separator.

**Comment by danrabbit** [comment]
Locale information comes from GLib, I believe so there's nothing we can do here to address this issue.

Closing as "Out of scope" since locale information isn't supplied by this code base
