### ISSUE TITLE
Formats dropdown is slow to navigate.

### ISSUE THREAD

**Issue by EidoJ** [elementary/switchboard-plug-locale#70]
scrolling down or up the list isn't intuitive, and is slow because are no scrollbar or obvious search methods. You have to hover over the upper or lower section of the list for it to start moving. Scrolling with the scrollwheel moves the list by half an item per tick.

**Comment by danrabbit** [comment]
Reopening because while sorting is fixed, a dropdown is still not ideal here

**Comment by peteruithoven** [comment]
Would be great to had a reusable filterable list Granite component. A bit like the component in the add popover in the Applications plug > Startup.

**Comment by peteruithoven** [comment]
Would be great to had a reusable filterable list Granite component? A bit like the widget that's used for adding a language.
