### ISSUE TITLE
Setting default temperature units depending on locale

### ISSUE THREAD

**Issue by gmikhail** [elementary/switchboard-plug-locale#81]
There may be a minor note, but I noticed that temperature units are not selected by default (none of them).  Specifically in the locale of Ukraine and Russia - Celsius degrees.

![2019-01-03 173830](https://user-images.githubusercontent.com/4838367/50699053-684f5080-104f-11e9-94d0-44ec97f47d95.png)

**Comment by danrabbit** [comment]
I think the issue is that on the backend the default selection is "automatic" and this is an override. I'm not sure if we can easily know which choice automatic implies here, but the simple thing we could do is switch this to a dropdown with the three options
