### ISSUE TITLE
Installing missing locales change the format value

### ISSUE THREAD

**Issue by romdef** [elementary/switchboard-plug-locale#83]
On Juno, after installing some applications, if I go back to the locale plug, it says some locales are missing. I can install them. But when it's complete, the value in the Format list is changed to 'Panama'. (I'm a french user and my default options are Region -> France & Format -> France (Français).

I can reproduce it every time I install a new app from apt which needs additional language packages.

**Comment by 4jNsY6fCVqZv** [comment]
Yes, the same happens to me for the selected region. The setting is lost when you click on a second installed language and switch back. What could a possible solution look like?

Also interesting, if I change the format of language A, it automatically changes language B to the same format. This also happens in the other direction.
Also when setting Fahrenheit or Celsius, the values for the other language are automatically adjusted for the other language.

My scenario: Two installed languages.
